name: Github Pages Publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: sterlingwes/gh-pages-deploy-action@v1.1
        with:
          access-token: ${{ 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 }}
          source-directory: ./web/dist/
          build-command: yarn build
